name: chat_bank
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: 3.0.0
  firebase_database : 11.0.0
  flutter_tts: ^3.5.2
  speech_to_text: 6.5.0
  permission_handler: 11.0.0
  http : 1.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
